question_data = [{"type": "boolean", "difficulty": "medium", "category": "History",
                  "question": "The Korean War ended in 1953 without any ceasefire.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Animals",
                  "question": "The Ceratosaurus, a dinosaur known for having a horn on the top of its nose, is also known to be a decendent of the Tyrannosaurus Rex.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium",
                  "category": "Entertainment: Video Games",
                  "question": "Metal Gear Solid V: The Phantom Pain runs on the Fox Engine.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "hard", "category": "History",
                  "question": "Joseph Stalins real name was Ioseb Bessarionis dze Dzugashvili.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Vehicles",
                  "question": "The Chevrolet Corvette has always been made exclusively with V8 engines only.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium",
                  "category": "Entertainment: Video Games",
                  "question": "Minecraft wasnt the original name to Minecraft.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy",
                  "category": "Entertainment: Video Games",
                  "question": "Each piece in Tetris is called a tetris.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Sports",
                  "question": "There are a total of 20 races in Formula One 2016 season.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium",
                  "category": "Entertainment: Video Games",
                  "question": "In Team Fortress 2, the Bills Hat is a reference to the game Dota 2.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Vehicles",
                  "question": "The Japanese Shinkansen beat the French TGVs speed record for fastest electric rail train.",
                  "correct_answer": "False", "incorrect_answers": ["True"]}]
